### PR TITLE
added the 'How to get into Hacking' and 'Web Security' sections to the guide

### PR DESCRIPTION
**Pull request by 7h3f0x**

### CODE REVIEW

**Comment by periperidip** [comment]
How do you think it would be if we were to put all these under the banner of InfoSec and make subsections of the respective fields?

**Comment by 7h3f0x** [comment]
that would make it more sorted I think, sounds good

**Comment by periperidip** [comment]
are you working on it?

**Comment by 7h3f0x** [comment]
haven't done anything yet, can do if it's decided

**Comment by periperidip** [comment]
Decide on what?

**Comment by 7h3f0x** [comment]
to make a more general infosec section and put the related subsections inside it

**Comment by periperidip** [comment]
> to make a more general infosec section and put the related subsections inside it

I am a bit confused here. We decided that the whole InfoSec section should be under one banner right? With many subsections. Where is the issue then?

**Comment by 7h3f0x** [comment]
i was sort of asking for your confirmation  :sweat_smile:

**Comment by periperidip** [comment]
> i was sort of asking for your confirmation

areee
yes yes you have the confirmation now XD
kholu == lovee

**Comment by 7h3f0x** [comment]
the deed is done

**Comment by periperidip** [comment]
Nice! Will merge

**Pull request merged**
