### PR TITLE
Added Game Development Section

### PR DESCRIPTION
**Pull request by simpuid**
I hope that it's grammatically correct. **Typora** changed some parts of other section (indentation and empty lines only)

### CODE REVIEW

**Comment by periperidip** [comment]
LGTM.
You added Gamasutra, **you're a man of culture I see** ;)
Would you recommend `gamedev.net`?  Also, I think there is a website, which hosted/had links to game jams? Do you remember the name?

Thank for correcting my whitespace error BTW :)

**Comment by simpuid** [comment]
I forgot about [gamedev.net](gamedev.net)
>  Also, I think there is a website, which hosted/had links to game jams? Do you remember the name?

Are talking about [itch.io](https://itch.io/jams) or [this](http://www.indiegamejams.com/)?

**Comment by simpuid** [comment]
Also add something about googling skills. It's the best advice one can give.

**Comment by periperidip** [comment]
> I forgot about [gamedev.net](gamedev.net)

Add it please?

> > Also, I think there is a website, which hosted/had links to game jams? Do you remember the name?
> 
> Are talking about [itch.io](https://itch.io/jams) or [this](http://www.indiegamejams.com/)?

The latter.

**Comment by periperidip** [comment]
I am merging this. Do add stuff if you feel like later ;)

**Pull request merged**
